#hibernate.hbm2ddl.auto=create
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:file:~/sample;INIT=CREATE SCHEMA IF NOT EXISTS DATABASE
    username: "sa"
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /console